print("ENTER NAME;")
NAME= input ()
print("ENTER ORG;")
ORG= input ()
print("ENTER CONTACT;")
CONTACT= input ()
print("ENTER ACCESS;")
ACCESS= input ()


print("+-------------------------------------+")
print("|-------APEX ENTERTAINMENT PASS-------|")
print("|-------------------------------------|")
print("| NAME:" + NAME.ljust(31) + "|")
print("| ORG:" + ORG.ljust(32) + "|")
print("| CONTACT:" + CONTACT.ljust(28) + "|")
print("| ACCESS:" + ACCESS.ljust(29) + "|")
print("| ISSUER: BCH Software Terminal System|")
print("|-------------------------------------|")
print("+-------------------------------------+")

